name: emergency_map
description: Google emergency map.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: 4.0.2
  google_maps_flutter: 2.5.0
  geolocator: 10.0.1
  get_it: 7.6.4
  dio: 5.3.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: 1.0.0
  coverage: 1.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/